import { business, type Locale } from "@/lib/config";
export function tr<T>(lang: Locale, de: T, en: T, uk: T, ru: T): T {
  return { de, en, uk, ru }[lang];
}
export function copy(l: Locale) {
  return {
    nav: tr(
      l,
      ["Google Ads", "ChatGPT Ads", "Blog", "Über uns", "Preise"],
      ["Google Ads", "ChatGPT Ads", "Blog", "About", "Pricing"],
      ["Google Ads", "ChatGPT Ads", "Blog", "Про AD4GROWTH", "Ціни"],
      ["Google Ads", "ChatGPT Ads", "Blog", "Об AD4GROWTH", "Цены"],
    ),
    cta: tr(
      l,
      "Projekt anfragen",
      "Discuss your project",
      "Обговорити проєкт",
      "Обсудить проект",
    ),
    intro: tr(
      l,
      "Google Ads und ChatGPT Ads.\nAus konkreter Nachfrage wird messbares Geschäft.",
      "Google Ads and ChatGPT Ads.\nTurn meaningful intent into measurable business.",
      "Google Ads та ChatGPT Ads.\nПеретворюємо попит на вимірюваний результат.",
      "Google Ads и ChatGPT Ads.\nПревращаем спрос в измеримый результат.",
    ),
    oneTime: tr(
      l,
      "SETUP · EINMALIG",
      "SETUP · ONE-TIME",
      "НАЛАШТУВАННЯ · РАЗОВО",
      "НАСТРОЙКА · РАЗОВО",
    ),
    media: tr(
      l,
      "Werbebudget separat",
      "Media budget separate",
      "Рекламний бюджет окремо",
      "Рекламный бюджет отдельно",
    ),
    serviceCta: (name: string) =>
      tr(
        l,
        `${name} anfragen`,
        `Discuss ${name}`,
        `Обговорити ${name}`,
        `Обсудить ${name}`,
      ),
    requestService: tr(l, "anfragen", "inquiry", "обговорити", "обсудить"),
    month: tr(l, "/ Monat", "/ month", "/ місяць", "/ месяц"),
    launchNote: !business.launch.active ? "" : tr(l,
      "LAUNCH PRICING · {n} PROJEKTE. Für die ersten drei Projekte gelten unsere Launch-Konditionen für Setup und Betreuung. Danach gelten für neue Projekte die regulären Konditionen.",
      "LAUNCH PRICING · {n} PROJECTS. The first three projects receive launch terms for setup and management. Regular terms apply to new projects afterwards.",
      "LAUNCH PRICING · {n} ПРОЄКТИ. Для перших трьох проєктів діють стартові умови налаштування та управління. Далі для нових проєктів діють стандартні умови.",
      "LAUNCH PRICING · {n} ПРОЕКТА. Для первых трёх проектов действуют стартовые условия настройки и управления. Далее для новых проектов действуют стандартные условия."),
    availability: tr(
      l,
      "ChatGPT Ads: Start nach Prüfung von Markt, Kontozugang und verfügbaren Messmöglichkeiten.",
      "ChatGPT Ads: launch subject to market, account access and measurement availability.",
      "ChatGPT Ads: запуск після перевірки ринку, доступу до акаунта та можливостей вимірювання.",
      "ChatGPT Ads: запуск после проверки рынка, доступа к аккаунту и возможностей измерения.",
    ),
    systemTitle: tr(
      l,
      ["Zwei Interfaces", "Ein Geschäftsziel"],
      ["Two interfaces", "One business objective"],
      ["Два інтерфейси", "Одна бізнес-мета"],
      ["Два интерфейса", "Одна бизнес-цель"],
    ),
    systemBody: tr(
      l,
      "Nachfrage entsteht an verschiedenen Orten. Entscheidend ist, was daraus wird: eine qualifizierte Anfrage, ein Kauf, ein neuer Kunde.",
      "Demand starts in different places. What matters is what follows: a qualified inquiry, a purchase, a new customer.",
      "Попит виникає в різних середовищах. Важливо, що відбувається далі: цільовий запит, покупка, новий клієнт.",
      "Спрос возникает в разных средах. Важно, что происходит дальше: целевой запрос, покупка, новый клиент.",
    ),
    search: tr(
      l,
      "Eine konkrete Suche. Ein erkennbarer Bedarf.",
      "A specific search. An identifiable need.",
      "Конкретний пошук. Зрозуміла потреба.",
      "Конкретный поиск. Понятная потребность.",
    ),
    conversation: tr(
      l,
      "Ein Gespräch. Ein Bedarf, der sich entwickelt.",
      "A conversation. A need taking shape.",
      "Розмова. Потреба, що формується.",
      "Разговор. Потребность, которая формируется.",
    ),
    mapTitle: tr(
      l,
      ["Nicht bei Klicks", "stehen bleiben"],
      ["Look beyond", "the click"],
      ["Дивіться далі", "за кліки"],
      ["Смотрите дальше", "кликов"],
    ),
    mapBody: tr(
      l,
      "Ein Werbekonto ist kein Selbstzweck. Wir verbinden Ausgaben mit Aktionen und Geschäftsergebnissen – soweit die Daten es zulassen.",
      "An ad account is a means to an end. We connect spend with actions and business outcomes, within the limits of the data.",
      "Рекламний акаунт — інструмент. Пов’язуємо витрати з діями та бізнес-результатами в межах доступних даних.",
      "Рекламный аккаунт — инструмент. Связываем расходы с действиями и результатами бизнеса в пределах доступных данных.",
    ),
    example: tr(
      l,
      "RECHENBEISPIEL · KEINE KUNDENERGEBNISSE",
      "ILLUSTRATIVE EXAMPLE · NOT CLIENT RESULTS",
      "НАВЧАЛЬНИЙ ПРИКЛАД · НЕ РЕЗУЛЬТАТИ КЛІЄНТІВ",
      "УЧЕБНЫЙ ПРИМЕР · НЕ РЕЗУЛЬТАТЫ КЛИЕНТОВ",
    ),
    stages: tr(
      l,
      [
        "Werbebudget",
        "Impressionen",
        "Klicks",
        "Conversions",
        "Kunden",
        "Umsatz",
        "Wachstum",
      ],
      [
        "Ad spend",
        "Impressions",
        "Clicks",
        "Conversions",
        "Customers",
        "Revenue",
        "Growth",
      ],
      [
        "Рекламний бюджет",
        "Покази",
        "Кліки",
        "Конверсії",
        "Клієнти",
        "Дохід",
        "Зростання",
      ],
      [
        "Рекламный бюджет",
        "Показы",
        "Клики",
        "Конверсии",
        "Клиенты",
        "Выручка",
        "Рост",
      ],
    ),
    stageNotes: tr(
      l,
      [
        "Kapital mit einem klaren Ziel einsetzen.",
        "Sichtbarkeit ist der Anfang, nicht das Ergebnis.",
        "Ein Klick zeigt Interesse, noch keinen Geschäftswert.",
        "Eine definierte Aktion: Anfrage, Kauf oder Buchung.",
        "CRM-Daten zeigen, welche Conversions zu Kunden werden.",
        "Zugeordneter Umsatz braucht nachvollziehbare Daten.",
        "Profitables Wachstum hängt auch von Marge, Bindung und Kapazität ab.",
      ],
      [
        "Invest with a defined objective.",
        "Visibility is a starting point, not an outcome.",
        "A click indicates interest, not yet business value.",
        "A defined action: inquiry, purchase or booking.",
        "CRM data reveals which conversions become customers.",
        "Attributed revenue needs traceable data.",
        "Profitable growth also depends on margin, retention and capacity.",
      ],
      [
        "Інвестувати з чіткою метою.",
        "Видимість — початок, а не результат.",
        "Клік означає інтерес, але ще не бізнес-цінність.",
        "Визначена дія: запит, покупка або бронювання.",
        "Дані CRM показують, які конверсії стають клієнтами.",
        "Для атрибуції доходу потрібні простежувані дані.",
        "Прибуткове зростання залежить також від маржі, утримання та ресурсів.",
      ],
      [
        "Инвестировать с понятной целью.",
        "Видимость — начало, а не результат.",
        "Клик означает интерес, но ещё не ценность для бизнеса.",
        "Определённое действие: заявка, покупка или бронирование.",
        "Данные CRM показывают, какие конверсии становятся клиентами.",
        "Для атрибуции выручки нужны прослеживаемые данные.",
        "Прибыльный рост зависит также от маржи, удержания и ресурсов.",
      ],
    ),
    servicesTitle: tr(
      l,
      "Fokussiert auf Nachfrage",
      "Focused on demand",
      "Фокус на попиті",
      "Фокус на спросе",
    ),
    googleShort: tr(
      l,
      "Menschen erreichen, die bereits nach Ihrem Angebot suchen. Suchintention, Kampagnenstruktur und Messung greifen ineinander.",
      "Reach people already searching for your offer. Search intent, campaign structure and measurement work together.",
      "Звертайтеся до людей, які вже шукають вашу пропозицію. Пошуковий намір, структура кампаній та вимірювання працюють разом.",
      "Обращайтесь к людям, которые уже ищут ваше предложение. Поисковый запрос, структура кампаний и измерение работают вместе.",
    ),
    chatShort: tr(
      l,
      "Kommerzielle Nachfrage im Gespräch verstehen. Ein eigenständiger Kanal mit eigener Logik – abhängig von Plattformzugang und verfügbaren Formaten.",
      "Understand commercial intent in conversation. A distinct channel with its own logic, subject to platform access and available formats.",
      "Розумійте комерційний намір у розмові. Окремий канал із власною логікою, залежний від доступу до платформи та форматів.",
      "Понимайте коммерческий запрос в разговоре. Отдельный канал со своей логикой, зависящий от доступа к платформе и форматов.",
    ),
    explore: tr(
      l,
      "Leistung ansehen",
      "Explore the service",
      "Докладніше про послугу",
      "Подробнее об услуге",
    ),
    processTitle: tr(
      l,
      "Ein System.\nFünf klare Schritte",
      "One system.\nFive clear steps",
      "Одна система.\nП’ять чітких кроків",
      "Одна система.\nПять чётких шагов",
    ),
    process: tr(
      l,
      [
        [
          "Verstehen",
          "Angebot, Nachfrage, Wirtschaftlichkeit und Conversion definieren.",
        ],
        ["Aufbauen", "Struktur, Anzeigen und belastbare Messung vorbereiten."],
        ["Starten", "Gezielt aktivieren. Erste Signale sammeln und prüfen."],
        [
          "Optimieren",
          "Suchanfragen, Budgets und Conversion-Qualität auswerten.",
        ],
        ["Skalieren", "Budget dort erhöhen, wo die Daten dafür sprechen."],
      ],
      [
        ["Understand", "Define the offer, demand, economics and conversion."],
        ["Build", "Prepare structure, ads and reliable measurement."],
        [
          "Launch",
          "Activate deliberately. Collect and validate early signals.",
        ],
        ["Optimize", "Review queries, budgets and conversion quality."],
        ["Scale", "Increase investment where the evidence supports it."],
      ],
      [
        ["Зрозуміти", "Визначити пропозицію, попит, економіку та конверсію."],
        [
          "Побудувати",
          "Підготувати структуру, оголошення та надійне вимірювання.",
        ],
        [
          "Запустити",
          "Активувати кампанії. Зібрати й перевірити перші сигнали.",
        ],
        ["Оптимізувати", "Аналізувати запити, бюджети та якість конверсій."],
        ["Масштабувати", "Збільшувати бюджет там, де це підтверджують дані."],
      ],
      [
        ["Понять", "Определить предложение, спрос, экономику и конверсию."],
        [
          "Построить",
          "Подготовить структуру, объявления и надёжное измерение.",
        ],
        [
          "Запустить",
          "Активировать кампании. Собрать и проверить первые сигналы.",
        ],
        [
          "Оптимизировать",
          "Анализировать запросы, бюджеты и качество конверсий.",
        ],
        [
          "Масштабировать",
          "Увеличивать бюджет там, где это подтверждают данные.",
        ],
      ],
    ),
    pricingTitle: tr(
      l,
      "Klare Leistung.\nKlare Kosten",
      "Clear scope.\nClear pricing",
      "Зрозуміла робота.\nПрозора ціна",
      "Понятная работа.\nПрозрачная цена",
    ),
    pricingBody: tr(
      l,
      "Ein Kanal oder beide. Einrichtung einmalig, Management monatlich. Das Werbebudget geht separat an die Plattform.",
      "One channel or both. One-time setup, monthly management. Media budget is paid separately to the platform.",
      "Один канал або обидва. Разове налаштування, щомісячне управління. Рекламний бюджет сплачується платформі окремо.",
      "Один канал или оба. Разовая настройка, ежемесячное управление. Рекламный бюджет оплачивается платформе отдельно.",
    ),
    launch: tr(l, "Zum Launch", "At launch", "На старті", "На старте"),
    taxNote: tr(l,
      "Alle Honorare sind Nettopreise für Geschäftskunden. Zuzüglich gesetzlicher Umsatzsteuer, soweit diese anfällt. Das Werbebudget wird separat an die Werbeplattform gezahlt und ist nicht im Betreuungshonorar enthalten.",
      "All fees are net B2B prices, plus statutory VAT where applicable. Media spend is paid separately to the advertising platform and is not included in management fees.",
      "Усі гонорари — нетто для бізнес-клієнтів; ПДВ додається, якщо застосовується. Рекламний бюджет сплачується платформі окремо та не входить у вартість управління.",
      "Все гонорары — нетто для бизнес-клиентов; НДС добавляется, если применим. Рекламный бюджет оплачивается платформе отдельно и не входит в стоимость управления."),
    fitTitle: tr(
      l,
      "Eine gute Basis\nfür den nächsten Schritt",
      "A solid foundation\nfor the next step",
      "Надійна основа\nдля наступного кроку",
      "Надёжная основа\nдля следующего шага",
    ),
    goodFit: tr(
      l,
      "Das passt",
      "A good fit",
      "Ми підходимо одне одному",
      "Мы подходим друг другу",
    ),
    notYet: tr(
      l,
      "Noch nicht der richtige Zeitpunkt",
      "Not quite ready yet",
      "Ще не час",
      "Пока не время",
    ),
    fitYes: tr(
      l,
      [
        "Klares Angebot und bestehende Nachfrage",
        "Funktionierende Website und messbares Ziel",
        "Realistisches Budget und Bereitschaft zu messen",
      ],
      [
        "Clear offer and existing demand",
        "Working website and a measurable objective",
        "Realistic budget and willingness to measure",
      ],
      [
        "Зрозуміла пропозиція та наявний попит",
        "Робочий сайт і вимірювана мета",
        "Реалістичний бюджет та готовність вимірювати",
      ],
      [
        "Понятное предложение и существующий спрос",
        "Рабочий сайт и измеримая цель",
        "Реалистичный бюджет и готовность измерять",
      ],
    ),
    fitNo: tr(
      l,
      [
        "Angebot oder Website noch nicht bereit",
        "Erwartung garantierter Umsätze",
        "Kein Budget für aussagekräftige Tests",
      ],
      [
        "Offer or website is not ready",
        "Expectation of guaranteed revenue",
        "No budget for meaningful tests",
      ],
      [
        "Пропозиція або сайт ще не готові",
        "Очікування гарантованого доходу",
        "Немає бюджету на змістовні тести",
      ],
      [
        "Предложение или сайт ещё не готовы",
        "Ожидание гарантированной выручки",
        "Нет бюджета на содержательные тесты",
      ],
    ),
    aboutLink: tr(
      l,
      "Mehr über den Ansatz",
      "More about the approach",
      "Докладніше про підхід",
      "Подробнее о подходе",
    ),
    contactTitle: tr(
      l,
      "Was soll Ihre Werbung\nfür Sie erreichen?",
      "What should your\nadvertising achieve?",
      "Чого має досягти\nваша реклама?",
      "Чего должна достичь\nваша реклама?",
    ),
    contactBody: tr(
      l,
      "Erzählen Sie von Ihrem Angebot und Ihrem Ziel. Wir klären schriftlich, ob und wie eine Zusammenarbeit sinnvoll ist. Kein Pflichttermin.",
      "Tell us about your offer and objective. We can explore the fit in writing. No mandatory call.",
      "Розкажіть про пропозицію та мету. Обговоримо письмово, чи є сенс працювати разом. Обов’язкового дзвінка немає.",
      "Расскажите о предложении и цели. Обсудим письменно, есть ли смысл работать вместе. Обязательного звонка нет.",
    ),
    faqTitle: tr(
      l,
      "Vor dem Start",
      "Before we start",
      "Перед стартом",
      "Перед стартом",
    ),
    faq: tr(
      l,
      [
        [
          "Ist das Werbebudget im Preis enthalten?",
          "Nein. Setup und Management sind die Leistungen von AD4GROWTH. Ihr Werbebudget wird separat an die jeweilige Plattform gezahlt.",
        ],
        [
          "Kann ich einen einzelnen Kanal buchen?",
          "Ja. Google Ads und ChatGPT Ads sind eigenständige Leistungen. Vor einem ChatGPT-Ads-Projekt prüfen wir die konkrete Verfügbarkeit.",
        ],
        [
          "Was passiert nach dem Setup?",
          "Im monatlichen Management prüfen wir Daten, Suchanfragen oder verfügbare Signale, optimieren Budget und Kampagnen und berichten über die vereinbarten Ziele.",
        ],
        [
          "Wie wird Performance gemessen?",
          "An einer zuvor definierten Conversion und ihrer Qualität. Soweit Daten verfügbar sind, verbinden wir diese mit Kunden und Umsatz.",
        ],
        [
          "Gibt es eine Mindestvertragslaufzeit?",
          "Die Zusammenarbeit ist auf Flexibilität ausgerichtet. Verbindliche Laufzeit und Kündigungsbedingungen werden im individuellen Angebot festgelegt.",
        ],
        [
          "Brauche ich bereits eine Website?",
          "Ja, eine funktionierende Website und eine klar definierte Conversion bilden die Grundlage.",
        ],
        [
          "Geht die Zusammenarbeit auch schriftlich?",
          "Ja. E-Mail kann der Hauptkanal sein. Weitere Kommunikationswege vereinbaren wir gemeinsam.",
        ],
      ],
      [
        [
          "Is media budget included?",
          "No. Setup and management cover the work of AD4GROWTH. Media budget is paid separately to the platform.",
        ],
        [
          "Can I book just one channel?",
          "Yes. Google Ads and ChatGPT Ads are separate services. We check specific availability before a ChatGPT Ads project.",
        ],
        [
          "What happens after setup?",
          "Monthly management reviews data, queries or available signals, adjusts budgets and campaigns, and reports against agreed goals.",
        ],
        [
          "How is performance measured?",
          "Through a defined conversion and its quality. Where data is available, we connect it to customers and revenue.",
        ],
        [
          "Is there a minimum contract term?",
          "The collaboration is designed to be flexible. Binding duration and cancellation terms are set in your individual proposal.",
        ],
        [
          "Do I need a website?",
          "Yes. A working website and a clearly defined conversion are the foundation.",
        ],
        [
          "Can we work mainly in writing?",
          "Yes. Email can be the primary channel. Other communication options are agreed together.",
        ],
      ],
      [
        [
          "Чи входить рекламний бюджет у ціну?",
          "Ні. Ціна покриває налаштування та управління AD4GROWTH. Рекламний бюджет сплачується платформі окремо.",
        ],
        [
          "Чи можна обрати один канал?",
          "Так. Google Ads і ChatGPT Ads — окремі послуги. Перед проєктом ChatGPT Ads перевіряємо конкретну доступність.",
        ],
        [
          "Що відбувається після налаштування?",
          "Щомісяця аналізуємо дані, запити або доступні сигнали, оптимізуємо бюджети й кампанії та звітуємо за узгодженими цілями.",
        ],
        [
          "Як вимірюється результат?",
          "За визначеною конверсією та її якістю. Якщо є дані, пов’язуємо їх із клієнтами та доходом.",
        ],
        [
          "Чи є мінімальний строк договору?",
          "Співпраця передбачає гнучкість. Обов’язкові строки та умови припинення узгоджуються в індивідуальній пропозиції.",
        ],
        [
          "Чи потрібен сайт?",
          "Так. Робочий сайт і чітко визначена конверсія — основа роботи.",
        ],
        [
          "Чи можна працювати переважно письмово?",
          "Так. Електронна пошта може бути основним каналом. Інші способи спілкування узгоджуємо разом.",
        ],
      ],
      [
        [
          "Входит ли рекламный бюджет в стоимость?",
          "Нет. Цена покрывает настройку и управление AD4GROWTH. Рекламный бюджет оплачивается платформе отдельно.",
        ],
        [
          "Можно выбрать один канал?",
          "Да. Google Ads и ChatGPT Ads — отдельные услуги. До проекта ChatGPT Ads проверяем конкретную доступность.",
        ],
        [
          "Что происходит после настройки?",
          "Ежемесячно анализируем данные, запросы или доступные сигналы, оптимизируем бюджеты и кампании, отчитываемся по согласованным целям.",
        ],
        [
          "Как измеряется результат?",
          "По определённой конверсии и её качеству. При наличии данных связываем их с клиентами и выручкой.",
        ],
        [
          "Есть минимальный срок договора?",
          "Сотрудничество предполагает гибкость. Обязательные сроки и условия прекращения согласуются в индивидуальном предложении.",
        ],
        [
          "Нужен ли сайт?",
          "Да. Рабочий сайт и чётко определённая конверсия — основа работы.",
        ],
        [
          "Можно работать преимущественно письменно?",
          "Да. Электронная почта может быть основным каналом. Другие способы общения согласуем вместе.",
        ],
      ],
    ),
    privacy: tr(
      l,
      "Datenschutz",
      "Privacy",
      "Конфіденційність",
      "Конфиденциальность",
    ),
    imprint: tr(
      l,
      "Impressum",
      "Legal notice",
      "Правова інформація",
      "Правовая информация",
    ),
    contact: tr(l, "Kontakt", "Contact", "Контакти", "Контакты"),
    home: tr(l, "Startseite", "Home", "Головна", "Главная"),
    skip: tr(l, "Zum Inhalt", "Skip to content", "До вмісту", "К содержимому"),
  };
}
